version: "3.7"
services:
  php:
    image: php:fpm-alpine
    restart: always
    volumes:
      - ./:/var/www/
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8877:80"
    volumes:
      - ./:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
